seed: 42
img_size: [224, 224]
batch_size: 32
epochs: 30
train_csv: "data/train.csv"
val_csv: "data/valid.csv"
test_csv: "data/test.csv"
train_dir: "data/train"
val_dir: "data/val"
test_dir: "data/test"
model_dir: "models"
output_dir: "outputs"
log_dir: "logs"
learning_rate: 0.0001